pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        JAVA_HOME   = 'C:\\Program Files\\Java\\jdk-25'
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/miska-voutilainen/in-class-assignments-otp2.git'
            }
        }

        stage('Build') {
            steps {
                dir('week5-jenkins') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('week5-jenkins') {
                    bat 'mvn test'
                }
            }
            post {
                always {
                    junit 'week5-jenkins/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('week5-jenkins') {
                    bat 'mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miska-voutilainen -Dsonar.login=%SONAR_TOKEN%'
                }
            }
        }

    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
