pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        JAVA_HOME            = 'C:\\Program Files\\Java\\jdk-21'
        SONARQUBE_SERVER     = 'SonarQubeServer'
        SONAR_TOKEN          = credentials('sonar-token')
        DOCKERHUB_CREDENTIALS_ID = 'Docker_Hub'
        DOCKERHUB_REPO       = 'miskav/week5-fuel-calculator'
        DOCKER_IMAGE_TAG     = 'latest'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/miska-voutilainen/in-class-assignments-otp2.git'
            }
        }

        stage('Build') {
            steps {
                dir('week5-jenkins') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Test & Coverage') {
            steps {
                dir('week5-jenkins') {
                    bat 'mvn test'
                }
            }
            post {
                always {
                    junit 'week5-jenkins/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('week5-jenkins') {
                    withSonarQubeEnv('SonarQubeServer') {
                        bat """
                            mvn sonar:sonar ^
                            -Dsonar.projectKey=week5-fuel-calculator ^
                            -Dsonar.projectName=week5-fuel-calculator ^
                            -Dsonar.host.url=http://localhost:9000 ^
                            -Dsonar.token=%SONAR_TOKEN% ^
                            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('week5-jenkins') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully. Image pushed to Docker Hub.'
        }
        failure {
            echo 'Pipeline failed. Check the logs above.'
        }
    }
}
